openapi: 3.0.1
info:
  title: Hypixel Skyblock Inventory API
  description: API to retrieve and cache parsed inventory data from Hypixel Skyblock profiles.
  version: 1.0.0
servers:
  - url: http://localhost:4321/api #  Adjust to your deployment URL
    description: Local development server
paths:
  /{player}/{profile}/accessorybag:
    get:
      summary: Get parsed accessory bag data
      description: Retrieves and parses the accessory bag contents for a given player and profile.
      parameters:
        - in: path
          name: player
          schema:
            type: string
          required: true
          description: The UUID of the player.
        - in: path
          name: profile
          schema:
            type: string
          required: true
          description: The UUID of the Skyblock profile.
      responses:
        '200':
          description: Successfully parsed accessory bag data.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Inventory'
        '400':
          description: Bad request (e.g., missing player or profile UUID, or player does not have the specified profile).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /{player}/{profile}/inventory:
    get:
      summary: Get parsed inventory data
      description: Retrieves and parses the main inventory contents for a given player and profile.
      parameters:
        - in: path
          name: player
          schema:
            type: string
          required: true
          description: The UUID of the player.
        - in: path
          name: profile
          schema:
            type: string
          required: true
          description: The UUID of the Skyblock profile.
      responses:
        '200':
          description: Successfully parsed inventory data.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Inventory'
        '400':
          description: Bad request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /{player}/{profile}/enderchest:
    get:
      summary: Get parsed ender chest data
      description: Retrieves and parses the ender chest contents for a given player and profile.
      parameters:
        - in: path
          name: player
          schema:
            type: string
          required: true
          description: The UUID of the player.
        - in: path
          name: profile
          schema:
            type: string
          required: true
          description: The UUID of the Skyblock profile.
      responses:
        '200':
          description: Successfully parsed ender chest data.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Inventory'
        '400':
          description: Bad request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /{player}/{profile}/cache:
    post:
      summary: Cache player profile data
      description: Fetches and caches the Skyblock profile data for a given player.
      parameters:
        - in: path
          name: player
          schema:
            type: string
          required: true
          description: The UUID of the player.
        - in: path
          name: profile
          schema:
            type: string
          required: true
          description: The UUID of the Skyblock profile.
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                ttl:
                  type: integer
                  description: Time to live for the cache entry (in milliseconds). Defaults to 3600000 (1 hour).
      responses:
        '200':
          description: Successfully cached player profile data.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
        '400':
          description: Bad request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Inventory:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/ParsedItem'
    ParsedItem:
      type: object
      properties:
        id:
          type: string
          description: The Hypixel Skyblock item ID.
        name:
          type: string
          description: The name of the item.
        description:
          type: string
          description: The item's description (lore).
        rarity:
          type: string
          enum: [COMMON, UNCOMMON, RARE, EPIC, LEGENDARY, MYTHIC, SPECIAL]
          description: The rarity of the item.
        type:
          type: string
          enum: [SWORD, BOW, ARMOR, ACCESSORY, CONSUMABLE, MISC]
          description: The type of the item.
        count:
          type: integer
          description: The number of items in the stack.
        stats:
          type: object
          additionalProperties:
            type: object
            properties:
              regular:
                type: number
              dungeon:
                type: number
                nullable: true
          description: Item stats (e.g., Damage, Strength, Crit Chance).
        flags:
          type: object
          properties:
            isUnbreakable:
              type: boolean
            isDungeonItem:
              type: boolean
            isCoopSoulbound:
              type: boolean
            isStarred:
              type: boolean
            hasHotPotatoBooks:
              type: integer
        ability:
          type: object
          nullable: true
          properties:
            name:
              type: string
            description:
              type: string
            manaCost:
              type: integer
              nullable: true
            cooldown:
              type: string
              nullable: true
            soulflowCost:
              type: integer
              nullable: true
            charges:
              type: object
              nullable: true
              properties:
                current:
                  type: integer
                maximum:
                  type: integer
                rechargeTime:
                  type: string
        modifier:
          type: string
          nullable: true
          description: The item's reforge.
        runes:
          type: object
          nullable: true
          additionalProperties:
            type: integer
          description: The runes applied to the item.
    Error:
      type: object
      properties:
        success:
          type: boolean
          example: false
        error:
          type: string
          description: The error message.
